"""add pending users

Revision ID: b7a9d3c5e381
Revises: 60c28afbe1c7
Create Date: 2026-07-21 09:06:18.693617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a9d3c5e381'
down_revision: Union[str, Sequence[str], None] = '60c28afbe1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_pending_users_id'), 'pending_users', ['id'], unique=False)
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pending_users_id'), table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###
